# Site settings
title: Bamboo Creative
email: info@bamboocreative.com
description: > # this means to ignore newlines until "baseurl:"
  A digital agency in Northern California
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: feeltheboo
github_username:  bamboocreative.com

# Build settings
markdown: kramdown
sass:
  sass_dir: scss
  
exclude: [scss, README.md, node_modules]
  
