# Site settings
title: Bamboo Creative
email: info@bamboocreative.com
description: > # this means to ignore newlines until "baseurl:"
  A digital agency in Northern California
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: feeltheboo
github_username:  bamboocreative

# Blog Settings
permalink: blog/:title/
paginate: 5
paginate_path: "blog/page:num"

# Archive Settings/Config

gems:
  - jekyll-archives
jekyll-archives:
  layout: archive                  # The default layout to use for archive pages.
  enabled:                         # Specifies which archives are enabled.
    - categories
#   layouts:                         # (Optional) Specifies type-specific layouts.
#
#     month:    month-archive
  permalinks:                      # (Optional) The permalinks to use for each archive.
    category: '/blog/:name/'

# Build settings
markdown: kramdown
sass:
  sass_dir: scss
  
exclude: [scss, README.md, node_modules, gruntfile.js, package.json]

collections:
  project:
    output: true
  people:
    output: true #Set to true for user profiles

# Configs prose.io for external editing
prose:
    rooturl: '_posts'
    site: 'bamboocreative.github.io'
    media: 'media'
    metadata:
        _posts:
            -   name: "layout"
                field:
                    element: "hidden"
                    value: "post"
            -   name: "title"
                field:
                    element: "text"
                    label: "title"
            -   name: "categories"
                field:
                    element: "multiselect"
                    label: "Add Categories"
                    placeholder: "Choose Categories.."
                    options:
                        -   name: "Bamboo"
                            value: "bamboo"
                        -   name: "Web"
                            value: "web"
                        -   name: "Design"
                            value: "design"
                        -   name: "Productivity"
                            value: "productivity"
            -   name: "body-class"
                field:
                    element: "hidden"
                    value: "body-class"
            -   name: "author"
                field:
                    element: "select"
                    label: "Choose Author"
                    placeholder: "Choose Author.."
                    options:
                        -   name: "Bamboo"
                            value: "Bamboo"
                        -   name: "CJ Alvarado"
                            value: "CJ Alvarado"
                        -   name: "Ginny Townsend"
                            value: "Ginny Townsend"
                        -   name: "Ben Derienzo"
                            value: "Ben Derienzo"
                        -   name: "Jake Elia"
                            value: "Jake Elia"
                        -   name: "Garrett Boatman"
                            value: "Garrett Boatman"
                        -   name: "Josh Reeder-Esparza"
                            value: "Josh Reeder-Esparza"
                        -   name: "Angie Wysocki"
                            value: "Angie Wysocki"
                        -   name: "Emily Lockteff"
                            value: "Emily Lockteff"
