# Site settings
title: Bamboo Creative
tagline: Executing beautiful ideas in Northern California. We push our clients to exceed their goals. Sometimes, that includes creative strategy, branding, design and product development.
url: "https://bamboocreative.com" # the base hostname & protocol for your site
post_dirs: false

# Social
socialimg: /images/social.jpg
facebook: bamboocreative
twitter: feeltheboo
github: bamboocreative
googleplus: 112568524891449759610
instagram: feeltheboo

# Contact
phone: 1 (855) try-bamboo
actual_phone: 1 (855) 879-2262
email: info@bamboocreative.com
address: '1601 Alhambra Blvd, Suite 100 <br>Sacramento, CA 95816'
address-map: https://goo.gl/maps/WA16bHj2P1oFEs246


# Blog Settings
permalink: blog/:title/
paginate: 100
paginate_path: "blog/page:num"

# We need a sitemap
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown

sass:
  style: :compressed

exclude: [scss, README.md, node_modules, gruntfile.js, package.json]

collections:
  project:
    output: true
    permalink: /our-work/:path/
    output_ext: false

  people:
    output: true

# All Bamboo Employees
authors:
  cjalvarado:
  alejandroreyes:

logos: 
  - image: '/images/logos/rocklin.png'
    name: 'City of Rocklin'
  - image: '/images/logos/stanford.png'
    name: 'Stanford University'
  - image: '/images/logos/bayside.png'
    name: 'Bayside Church'
  - image: '/images/logos/booklaunch.png'
    name: 'Booklaunch'
  - image: '/images/logos/chic.png'
    name: 'CHICH Conference'
  - image: '/images/logos/abs.png'
    name: 'American Bible Society'
  - image: '/images/logos/snippet.png'
    name: 'The Snippet App'
  - image: '/images/logos/zocalo.png'
    name: 'Zocalo'
