# Site settings
title: Bamboo Creative
tagline: Executing beautiful ideas in Northern California. We push our clients to exceed their goals. Sometimes, that includes creative strategy, branding, design and product development.
url: "https://bamboocreative.com" # the base hostname & protocol for your site

# Social
socialimg: /images/social.jpg
facebook: bamboocreative
twitter: feeltheboo
github: bamboocreative
googleplus: 112568524891449759610
instagram: feeltheboo

# Contact
phone: 1 (855) trybamboo
email: hello


# Blog Settings
permalink: blog/:title/
paginate: 8
paginate_path: "blog/page:num"

# We need a sitemap
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: :compressed
  
exclude: [scss, README.md, node_modules, gruntfile.js, package.json]

collections:
  project:
    output: true
  people:
    output: true

# All Bamboo Employees
authors:
  cjalvarado:
  alejandroreyes: