# Site settings
title: Bamboo Creative
tagline: Executing beautiful ideas in Northern California. We push our clients to exceed their goals. Sometimes, that includes creative strategy, branding, design and product development.
url: "https://bamboocreative.com" # the base hostname & protocol for your site
post_dirs: false

# Social
socialimg: /images/social.jpg
facebook: bamboocreative
twitter: feeltheboo
github: bamboocreative
googleplus: 112568524891449759610
instagram: feeltheboo

# Contact
phone: 1 (855) try-bamboo
email: hello@bamboocreative.com
address: '6020 W Oaks Blvd. Suite 180<br>Rocklin, CA 95765'
address-map: https://www.google.com/maps/place/6020+W+Oaks+Blvd+%23180,+Rocklin,+CA+95765/@38.8108335,-121.2872651,14z/data=!4m2!3m1!1s0x809b223dbf4116d1:0x7d9095bd5be386f6?hl=en-US


# Blog Settings
permalink: blog/:title/
paginate: 8
paginate_path: "blog/page:num"

# We need a sitemap
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: :compressed
  
exclude: [scss, README.md, node_modules, gruntfile.js, package.json]

collections:
  project:
    output: true
    permalink: /project/:path/
    output_ext: false
    
  people:
    output: true
    
# All Bamboo Employees
authors:
  cjalvarado:
  alejandroreyes: